language: bash

os:
  - linux

services: docker

before_script:
  - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
  - cp env_travis .env
script:
  - docker-compose build

deploy:
  provider: script
  script: docker-compose push
  skip_cleanup: true
  on:
    all_branches: true

