language: bash

os:
  - linux

services: docker

before_script:
  - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
  - cp .env_travis .env
  - pip install --user shyaml

script:
  - docker-compose build xcube-python-base
  - docker-compose build xcube
  - docker-compose build xcube-gen
  - docker-compose build xcube-jupyterlab
  - docker-compose build xcube-viewer

deploy:
  provider: script
  script: docker-compose push
  skip_cleanup: true
  on:
    all_branches: true

