language: generic

os:
  - linux

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info -a
  - conda install conda-verify conda-build anaconda-client

script:
  - conda build -c conda-forge -c default xcube

after_success:
  - anaconda -v -t ${anaconda_token} upload /home/travis/miniconda/conda-bld/linux-64/xcube-0.2.0.dev3-py36_0.tar.bz2 -u bc-dev --force
  - anaconda -v -t ${anaconda_token} upload /home/travis/miniconda/conda-bld/linux-64/xcube-0.2.0.dev3-py37_0.tar.bz2 -u bc-dev --force
  - .  upload_to_anaconda_cloud.sh xcube