language: generic

env:
  global:
    - CONDA_PY=3.7

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set anaconda_upload yes
  - conda update conda
  - conda info -a
  - conda install conda-verify conda-build

script:
  - conda build -c conda-forge xcube
  - ./upload_to_anaconda_cloud.sh xcube
