image: Ubuntu

install:
  - sh: docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
  - sh: pip install --user shyaml
  - sh: sudo apt-get -y update
  - sh: sudo apt-get -y install docker-compose

build_script:
  - sh: docker-compose build xcube-python-base
  - sh: docker-compose build xcube
  - sh: docker-compose build xcube-gen
  - sh: docker-compose build xcube-geodb
  - sh: docker-compose build xcube-jupyterlab
  - sh: docker-compose build --build-arg SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY}" xcubehub-base

deploy_script:
  - sh: docker-compose push
#  - sh: >-
#    if [ -n "$APPVEYOR_REPO_TAG_NAME" ]; then
#      docker-compose push
#    fi;