version: '3'

services:
  xcube-python-base:
    build:
      context: .
      dockerfile: xcube-python-base.dockerfile
      args:
        - XCUBE_VERSION=${XCUBE_VERSION}
        - XCUBE_DOCKER_VERSION=${XCUBE_DOCKER_VERSION}
        - XCUBE_USER_NAME=${XCUBE_USER_NAME}
        - MINICONDA_VERSION=${MINICONDA_VERSION}
    image: quay.io/bcdev/xcube-python-base:${XCUBE_PYTHON_BASE_VERSION}
  xcube:
    build:
      context: .
      dockerfile: xcube.dockerfile
      args:
        - XCUBE_VERSION=${XCUBE_VERSION}
        - XCUBE_DOCKER_VERSION=${XCUBE_DOCKER_VERSION}
        - XCUBE_USER_NAME=${XCUBE_USER_NAME}
        - XCUBE_PYTHON_BASE_VERSION=${XCUBE_PYTHON_BASE_VERSION}
    image: quay.io/bcdev/xcube:${XCUBE_VERSION}
    ports:
      - 4000:4000
  xcube-gen:
    build:
      context: .
      dockerfile: xcube-gen.dockerfile
      args:
        - XCUBE_VERSION=${XCUBE_VERSION}
        - XCUBE_DOCKER_VERSION=${XCUBE_DOCKER_VERSION}
        - XCUBE_USER_NAME=${XCUBE_USER_NAME}
        - XCUBE_SH_VERSION=${XCUBE_SH_VERSION}
        - XCUBE_CCI_VERSION=${XCUBE_CCI_VERSION}
        - XCUBE_CDS_VERSION=${XCUBE_CDS_VERSION}
    image: quay.io/bcdev/xcube-gen:${XCUBE_GEN_VERSION}
    ports:
      - 8000:8000
    volumes:
      - ./:/workspace
  xcube-jupyterlab:
    build:
      context: .
      dockerfile: xcube-jupyterlab.docker
      args:
        - XCUBE_VERSION=${XCUBE_VERSION}
        - XCUBE_DOCKER_VERSION=${XCUBE_DOCKER_VERSION}
        - XCUBE_USER_NAME=${XCUBE_USER_NAME}
    image: quay.io/bcdev/xcube-jupyterlab:${XCUBE_VERSION}
    ports:
      - "8888:8888"
  xcubehub-base:
    build:
      context: .
      dockerfile: xcubehub-base.docker
      args:
        - XCUBEHUB_BASE_VERSION=${XCUBEHUB_BASE_VERSION}
        - XCUBEHUB_VERSION=${XCUBEHUB_VERSION}
        - XCUBE_USER_NAME=${XCUBE_USER_NAME}
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    image: quay.io/bcdev/xcubehub-base:${XCUBE_VERSION}
    ports:
      - "4000:4000"
