sentinelhub:
  title: SENTINEL Hub (Central Europe)
  description: Datasets from the SENTINEL Hub API deployment in Central Europe
  store_id: sentinelhub
  store_params:
    api_url: https://services.sentinel-hub.com

#sentinelhub_uswest:
#  title: SENTINEL Hub (US-West)
#  description: Datasets from the SENTINEL Hub API deployment in US West
#  store_id: sentinelhub
#  store_params:
#    api_url: https://services-uswest2.sentinel-hub.com

sentinelhub_creodias:
  title: SENTINEL Hub (CreoDIAS)
  description: Datasets from the SENTINEL Hub API deployment on CreoDIAS
  store_id: sentinelhub
  store_params:
    api_url: https://creodias.sentinel-hub.com

#sentinelhub_mundi:
#  title: SENTINEL Hub (Mundi)
#  description: Datasets from the SENTINEL Hub API deployment on Mundi
#  store_id: sentinelhub
#  store_params:
#    api_url: https://shservices.mundiwebservices.com
#
#sentinelhub_codede:
#  title: SENTINEL Hub (CODE-DE)
#  description: Datasets from the SENTINEL Hub API deployment on CODE-DE
#  store_id: sentinelhub
#  store_params:
#    api_url: https://code-de.sentinel-hub.com

cds:
  title: C3S Climate Data Store (CDS)
  description: Selected datasets from the Copernicus CDS API
  store_id: cds

cciodp:
  title: ESA Climate Change Initiative (CCI)
  description: Data from the ESA CCI Open Data Portal API
  store_id: cciodp
