# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

package:
  name: xcube
  version: "0.2.0.dev3"

build:
  number: 0
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - xcube = xcube.cli.cli:main
    - xcube-gen = xcube.cli.gen:main
    - xcube-restime = xcube.cli.restime:main

source:
  # git_rev: 0.2.0.dev3
  git_url: https://github.com/dcs4cop/xcube

requirements:
  build:
    # Required
    - click =7.0
  run:
    - click =7.0
  test:
    # Testing
    - flake8 =3.7
    - pytest =4.4
    - pytest-cov =2.6

test:
  # Python imports
  imports:
    - xcube

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - xcube --help

  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov

about:
  summary: "XCube"
  home: https://github.com/dcs4cop/xcube
  license: MIT
  license_file: LICENSE
